development:
  log_level: debug
  log_file_path: ./inout.log 
  web_port: 80
  provider:
    TrustCommerce:
      tenant: pgs-testTelecash
      shop: shop-InOut
      shopInfo: A. Bernolaka 72, Zilina
      # host: http://localhost:8080

      # IBM cloud
      # host: https://preprod-entervo-connectv2.scheidt-bachmann.net:8443
      # host: https://entervo-connectv2.scheidt-bachmann.net:8443
      # baseURL: /pgs/public/api/payment

      # AWS cloud
      host: https://kong.dev.parking.scheidt-bachmann.net/pgs/
      # host: https://pm.preprod.parking.scheidt-bachmann.net/pgs/
      # host: https://pm.prod.parking.scheidt-bachmann.net/pgs/
      baseURL: public/api/payment

      successURL: http://localhost/approved
      failureURL: http://localhost/declined
      locale: en-GB
      costCentre: 2014615
      imageColor: true

production:
  log_level: debug
  log_file_path: ./inout.log
  web_port: 80
  provider:
    TrustCommerce:
      tenant: pgs-testCCV
      #tenant: DE-Heidelberg-P6-Kraus
      shop: shop-InOut
      shopInfo: A. Bernolaka 72, Zilina
      # host: http://localhost:8080

      # IBM cloud
      # host: https://preprod-entervo-connectv2.scheidt-bachmann.net:8443
      # host: https://entervo-connectv2.scheidt-bachmann.net:8443
      # baseURL: /pgs/public/api/payment

      # AWS cloud
      host: https://kong.dev.parking.scheidt-bachmann.net/pgs/
      # host: https://pm.preprod.parking.scheidt-bachmann.net/pgs/
      # host: https://pm.prod.parking.scheidt-bachmann.net/pgs/
      baseURL: public/api/payment

      successURL: http://localhost/approved
      failureURL: http://localhost/declined
      locale: en-GB
      costCentre: 2014615
      imageColor: true
